In [16]:
import pandas as pd
import numpy as np
from os import path
import random

In [57]:
nameList = ['^GDAXI', '^GSPC', '^HSI']
dirPath = "./data"
df_list = []
for csvName in nameList:
    df = pd.read_csv(path.join(dirPath, csvName+".csv"))
    df['Date'] = pd.to_datetime(df['Date'])
    df.set_index('Date', inplace=True)
    df_list.append(df)

In [76]:
def getClosestDateAfter(df, date):
    s = pd.to_datetime(df.index.to_series()) - pd.to_datetime(startDate)
    return s[s >= pd.Timedelta(0)].idxmin()

In [111]:
startDate = pd.to_datetime("2004-01-03")

In [99]:
closestDate = min([getClosestDateAfter(df, startDate) for df in df_list])

In [100]:
closestDate

Timestamp('2004-01-05 00:00:00')

In [86]:
df.loc[pd.to_datetime("2004-01-01"):pd.to_datetime("2004-01-01")+pd.Timedelta(days=5)]

Open          High           Low         Close  \
Date                                                                 
2004-01-01           NaN           NaN           NaN           NaN   
2004-01-02  12664.990234  12815.080078  12664.990234  12801.480469   
2004-01-05  12844.589844  13009.400391  12763.099609  13005.330078   
2004-01-06  13063.450195  13128.730469  12975.500000  13036.320313   

               Adj Close       Volume  
Date                                   
2004-01-01           NaN          NaN  
2004-01-02  12801.480469  305575000.0  
2004-01-05  13005.330078  362998400.0  
2004-01-06  13036.320313  440100800.0

In [108]:
if startDate in df.index:
    print([random.uniform(df.loc[startDate, "Low"], df.loc[startDate, "High"]) for df in df_list])

[4029.6138560390395, 1120.0978964958724, 12975.679302160917]


In [97]:
df.loc[pd.date_range(pd.to_datetime("2004-01-01"), pd.to_datetime("2004-01-01")+pd.Timedelta(days=5))]

/Users/lzcai/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:947: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike
  return getattr(section, self.name)[new_key]


2004-01-01             NaN
2004-01-02    12664.990234
2004-01-03             NaN
2004-01-04             NaN
2004-01-05    12844.589844
2004-01-06    13063.450195
Freq: D, Name: Open, dtype: float64

In [114]:

[random.uniform(
    df.loc[startDate, "Low"], 
    df.loc[startDate, "High"]) 
    if startDate in df.index
    else np.nan 
    for df in df_list]

[nan, nan, nan]

In [129]:
a = np.array([np.nan, 3, 4, np.nan, 1, 2])
np.isnan(a)

array([ True, False, False,  True, False, False])

In [157]:
b = a*[1,-2,3,-4,5,6]
np.nansum(b)

23.0

In [149]:
c = b/np.nansum(b)

In [150]:
c

array([       nan, 0.17142857, 0.34285714,        nan, 0.14285714,
       0.34285714])

In [154]:
a

array([nan,  3.,  4., nan,  1.,  2.])

In [158]:
b/a

array([nan, -2.,  3., nan,  5.,  6.])

In [164]:
b*(b<0)

/Users/lzcai/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in less
  """Entry point for launching an IPython kernel.


array([nan, -6.,  0., nan,  0.,  0.])

In [172]:
np.nan_to_num(b)

array([ 0., -6., 12.,  0.,  5., 12.])

In [188]:
result = df_list[0].index
for df in df_list:
    result = np.intersect1d(result, df.index)


In [196]:
int((np.max(result) - np.min(result)).astype('timedelta64[D]') / np.timedelta64(1, 'D'))

10954

In [198]:
len(b)

6

In [10]:
[[0.0]*4]*3

[[0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]]

In [14]:
upper_bond = [[3.0]*4]
upper_bond+=[[1.0]*(4)]*2
upper_bond

[[3.0, 3.0, 3.0, 3.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]]

In [9]:
[3.0]+[1.0]*(3)

[3.0, 1.0, 1.0, 1.0]

In [28]:
a = np.array([0.5, 0.2, 1.3, 2.0])
b = np.floor(a).astype(int)
c = a*[b==0]

In [29]:
a*(1-c)

array([[0.25, 0.16, 1.3 , 2.  ]])

In [30]:
1-c

array([[0.5, 0.8, 1. , 1. ]])

In [33]:
[1.0]*(4-1) + [0.0]

[1.0, 1.0, 1.0, 0.0]

In [32]:
pd.read_csv("./data/^HSI.csv")

Date          Open          High           Low         Close  \
0     1986-12-31   2568.300049   2568.300049   2568.300049   2568.300049   
1     1987-01-01           NaN           NaN           NaN           NaN   
2     1987-01-02   2540.100098   2540.100098   2540.100098   2540.100098   
3     1987-01-05   2552.399902   2552.399902   2552.399902   2552.399902   
4     1987-01-06   2583.899902   2583.899902   2583.899902   2583.899902   
...          ...           ...           ...           ...           ...   
8428  2020-02-11  27514.250000  27674.810547  27436.990234  27583.880859   
8429  2020-02-12  27717.220703  27892.480469  27614.830078  27823.660156   
8430  2020-02-13  27953.650391  27953.650391  27695.599609  27730.000000   
8431  2020-02-14  27698.560547  27960.660156  27695.589844  27815.599609   
8432  2020-02-17  27766.710938  28055.580078  27766.710938  27959.599609   

         Adj Close        Volume  
0      2568.300049  0.000000e+00  
1              NaN           NaN  
2      2540.100098  0.000000e+00  
3      2552.399902  0.000000e+00  
4      2583.899902  0.000000e+00  
...            ...           ...  
8428  27583.880859  1.868625e+09  
8429  27823.660156  1.796561e+09  
8430  27730.000000  1.617010e+09  
8431  27815.599609  1.445336e+09  
8432  27959.599609  1.412999e+09  

[8433 rows x 7 columns]